apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/postgres.yaml
  - k8s/minio.yaml
  - k8s/pgadmin.yaml
  - k8s/api.yaml
  - k8s/admin.yaml
  - k8s/player.yaml
  - k8s/caddy.yaml

configMapGenerator:
  - name: futhub-caddy
    files:
      - Caddyfile
  - name: futhub-pgadmin
    files:
      - servers.json=pgadmin/servers.json
      - pgpass=pgadmin/pgpass

secretGenerator:
  - name: futhub-env
    envs:
      - .env
  - name: futhub-dotenv
    files:
      - dotenv=.env

generatorOptions:
  disableNameSuffixHash: true
