/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FutHub API
 * API do FutHub para jogo, automações Discord e administração.
 * OpenAPI spec version: 1.0
 */
import { request } from "./request.js";
export interface ReadonlyidstringnamestringpricenumberimageUrlstringcardsPerPacknumber {
  id: string;
  name: string;
  price: number;
  imageUrl: string;
  cardsPerPack: number;
}

export interface ReadonlypacksReadonlyidstringnamestringpricenumberimageUrlstringcardsPerPacknumberpagenumbertotalPagesnumber {
  packs: ReadonlyidstringnamestringpricenumberimageUrlstringcardsPerPacknumber[];
  page: number;
  totalPages: number;
}

export type BotResponseButtonDtoStyle =
  (typeof BotResponseButtonDtoStyle)[keyof typeof BotResponseButtonDtoStyle];

export const BotResponseButtonDtoStyle = {
  danger: "danger",
  link: "link",
  primary: "primary",
  secondary: "secondary",
  success: "success",
} as const;

export interface BotResponseButtonDto {
  /** @maxLength 80 */
  action: string;
  /**
   * @minLength 1
   * @maxLength 80
   */
  label: string;
  style: BotResponseButtonDtoStyle;
  /** @maxLength 512 */
  url: string;
  disabled: boolean;
}

/**
 * Grupo de componentes.
 */
export type BotResponseContainerDtoType =
  (typeof BotResponseContainerDtoType)[keyof typeof BotResponseContainerDtoType];

export const BotResponseContainerDtoType = {
  container: "container",
} as const;

/**
 * Imagem da mensagem.
 */
export type BotResponseMediaDtoType =
  (typeof BotResponseMediaDtoType)[keyof typeof BotResponseMediaDtoType];

export const BotResponseMediaDtoType = {
  media: "media",
} as const;

export interface BotResponseMediaDto {
  /** Imagem da mensagem. */
  type: BotResponseMediaDtoType;
  /** @maxLength 2048 */
  url: string;
  /** @maxLength 1024 */
  description: string;
}

/**
 * Linha de controles.
 */
export type BotResponseRowDtoType =
  (typeof BotResponseRowDtoType)[keyof typeof BotResponseRowDtoType];

export const BotResponseRowDtoType = {
  row: "row",
} as const;

export interface BotResponseRowDto {
  /** Linha de controles. */
  type: BotResponseRowDtoType;
  /**
   * @minItems 1
   * @maxItems 5
   */
  buttons: BotResponseButtonDto[];
}

/**
 * Separador visual.
 */
export type BotResponseSeparatorDtoType =
  (typeof BotResponseSeparatorDtoType)[keyof typeof BotResponseSeparatorDtoType];

export const BotResponseSeparatorDtoType = {
  separator: "separator",
} as const;

export type BotResponseSeparatorDtoSpacing =
  (typeof BotResponseSeparatorDtoSpacing)[keyof typeof BotResponseSeparatorDtoSpacing];

export const BotResponseSeparatorDtoSpacing = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface BotResponseSeparatorDto {
  /** Separador visual. */
  type: BotResponseSeparatorDtoType;
  spacing: BotResponseSeparatorDtoSpacing;
  divider: boolean;
}

/**
 * Texto da mensagem.
 */
export type BotResponseTextDtoType =
  (typeof BotResponseTextDtoType)[keyof typeof BotResponseTextDtoType];

export const BotResponseTextDtoType = {
  text: "text",
} as const;

export interface BotResponseTextDto {
  /** Texto da mensagem. */
  type: BotResponseTextDtoType;
  /**
   * @minLength 1
   * @maxLength 4000
   */
  content: string;
}

export interface BotResponseContainerDto {
  /** Grupo de componentes. */
  type: BotResponseContainerDtoType;
  /** @pattern ^(#[0-9A-Fa-f]{6})?$ */
  color: string;
  /**
   * @minItems 1
   * @maxItems 39
   */
  components: (
    | BotResponseMediaDto
    | BotResponseRowDto
    | BotResponseSeparatorDto
    | BotResponseTextDto
  )[];
}

export type BotResponseDefinitionDtoVariablesItem = {
  token: string;
  description: string;
  example: string;
};

export type BotResponseDefinitionDtoActionsItem = {
  id: string;
  label: string;
  description: string;
};

export type BotResponseTemplateDtoMode =
  (typeof BotResponseTemplateDtoMode)[keyof typeof BotResponseTemplateDtoMode];

export const BotResponseTemplateDtoMode = {
  components_v2: "components_v2",
  legacy: "legacy",
} as const;

export type BotResponseEmbedDtoFieldsItem = {
  /**
   * @minLength 1
   * @maxLength 256
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 1024
   */
  value: string;
  inline: boolean;
};

export interface BotResponseEmbedDto {
  /** @maxLength 256 */
  title: string;
  /** @maxLength 4096 */
  description: string;
  /** @pattern ^(#[0-9A-Fa-f]{6})?$ */
  color: string;
  /** @maxLength 2048 */
  footer: string;
  /** @maxLength 256 */
  authorName?: string;
  /** @maxLength 2048 */
  authorUrl?: string;
  /** @maxLength 2048 */
  authorIconUrl?: string;
  /** @maxLength 2048 */
  imageUrl: string;
  /** @maxLength 2048 */
  thumbnailUrl: string;
  /** @maxItems 25 */
  fields: BotResponseEmbedDtoFieldsItem[];
}

export interface BotResponseTemplateDto {
  mode: BotResponseTemplateDtoMode;
  /** @maxLength 2000 */
  content: string;
  /** @maxItems 10 */
  embeds: BotResponseEmbedDto[];
  /** @maxItems 40 */
  components: (
    | BotResponseContainerDto
    | BotResponseMediaDto
    | BotResponseRowDto
    | BotResponseSeparatorDto
    | BotResponseTextDto
  )[];
}

export interface BotResponseDefinitionDto {
  key: string;
  command: string;
  label: string;
  description: string;
  variables: BotResponseDefinitionDtoVariablesItem[];
  actions: BotResponseDefinitionDtoActionsItem[];
  defaultTemplate: BotResponseTemplateDto;
}

export type ListPackCatalog200Item = {
  id: string;
  name: string;
  emoji: string;
  cardsAmount: number;
  price: number;
  limitPerUser: number;
};

export type GetPackShopParams = {
  page?: number;
};

export type PurchasePackBodyIdentity = {
  id: string;
  name: string;
  /** @nullable */
  avatarUrl: string | null;
};

export type PurchasePackBody = {
  identity: PurchasePackBodyIdentity;
};

export type PurchasePack200 = {
  balance: number;
  quantity: number;
};

export type OpenPackBodyIdentity = {
  id: string;
  name: string;
  /** @nullable */
  avatarUrl: string | null;
};

export type OpenPackBody = {
  identity: OpenPackBodyIdentity;
};

export type OpenPack200CardsItemCard = {
  id: string;
  overall: number;
};

export type OpenPack200CardsItem = {
  id: string;
  card: OpenPack200CardsItemCard;
};

export type OpenPack200ProgressionRewardsItemType =
  (typeof OpenPack200ProgressionRewardsItemType)[keyof typeof OpenPack200ProgressionRewardsItemType];

export const OpenPack200ProgressionRewardsItemType = {
  balance: "balance",
  card: "card",
  field: "field",
  pack: "pack",
} as const;

export type OpenPack200ProgressionRewardsItem = {
  itemId: string;
  type: OpenPack200ProgressionRewardsItemType;
  quantity: number;
  /** @nullable */
  resourceId: string | null;
};

export type OpenPack200Progression = {
  gainedXp: number;
  level: number;
  xp: number;
  nextLevelXp: number;
  rewards: OpenPack200ProgressionRewardsItem[];
};

export type OpenPack200 = {
  cards: OpenPack200CardsItem[];
  progression: OpenPack200Progression;
};

export type ListMissionsBody = {
  id: string;
  name: string;
  /** @nullable */
  avatarUrl: string | null;
};

export type ListMissions200MissionsItemType =
  (typeof ListMissions200MissionsItemType)[keyof typeof ListMissions200MissionsItemType];

export const ListMissions200MissionsItemType = {
  claim_profit: "claim_profit",
  open_pack: "open_pack",
  play_match: "play_match",
  sell_player: "sell_player",
} as const;

export type ListMissions200MissionsItemCadence =
  (typeof ListMissions200MissionsItemCadence)[keyof typeof ListMissions200MissionsItemCadence];

export const ListMissions200MissionsItemCadence = {
  daily: "daily",
  monthly: "monthly",
  weekly: "weekly",
} as const;

export type ListMissions200MissionsItemRewardType =
  (typeof ListMissions200MissionsItemRewardType)[keyof typeof ListMissions200MissionsItemRewardType];

export const ListMissions200MissionsItemRewardType = {
  balance: "balance",
  card: "card",
  field: "field",
  pack: "pack",
  premium: "premium",
} as const;

/**
 * @nullable
 */
export type ListMissions200MissionsItemReward = {
  itemId: string;
  type: ListMissions200MissionsItemRewardType;
  quantity: number;
  /** @nullable */
  resourceId: string | null;
} | null;

export type ListMissions200MissionsItem = {
  id: string;
  title: string;
  type: ListMissions200MissionsItemType;
  cadence: ListMissions200MissionsItemCadence;
  tier: number;
  goal: number;
  progress: number;
  completed: boolean;
  claimed: boolean;
  expiresAt: string;
  /** @nullable */
  reward: ListMissions200MissionsItemReward;
};

export type ListMissions200 = {
  missions: ListMissions200MissionsItem[];
};

export type ExecuteLucroBody = {
  id: string;
  name: string;
  /** @nullable */
  avatarUrl: string | null;
};

export type ExecuteLucro200 =
  | {
      kind: "success";
      reward: {
        value: number;
        weight: number;
        message: string;
      };
      balance: number;
      availableAt: string;
      progression: {
        gainedXp: number;
        level: number;
        xp: number;
        nextLevelXp: number;
        rewards: {
          itemId: string;
          type: "balance" | "card" | "field" | "pack";
          quantity: number;
          /** @nullable */
          resourceId: string | null;
        }[];
      };
      embed: {
        title: string;
        description: string;
        color: string;
        footer: string;
      };
    }
  | {
      kind: "cooldown";
      availableAt: string;
    };

export type GetV1AdminLucro200RewardsItemMessages = {
  pt: string;
  es: string;
  en: string;
};

export type GetV1AdminLucro200RewardsItem = {
  value: number;
  weight: number;
  messages: GetV1AdminLucro200RewardsItemMessages;
  id: string;
};

export type GetV1AdminLucro200Embed = {
  title: string;
  description: string;
  color: string;
  footer: string;
};

export type GetV1AdminLucro200 = {
  cooldownSeconds: number;
  rewards: GetV1AdminLucro200RewardsItem[];
  embed: GetV1AdminLucro200Embed;
};

export type PutV1AdminLucroBodyRewardsItemMessages = {
  pt: string;
  es: string;
  en: string;
};

export type PutV1AdminLucroBodyRewardsItem = {
  value: number;
  weight: number;
  messages: PutV1AdminLucroBodyRewardsItemMessages;
};

export type PutV1AdminLucroBodyEmbed = {
  title: string;
  description: string;
  color: string;
  footer: string;
};

export type PutV1AdminLucroBody = {
  cooldownSeconds: number;
  rewards: PutV1AdminLucroBodyRewardsItem[];
  embed: PutV1AdminLucroBodyEmbed;
};

export type PutV1AdminLucro200RewardsItemMessages = {
  pt: string;
  es: string;
  en: string;
};

export type PutV1AdminLucro200RewardsItem = {
  value: number;
  weight: number;
  messages: PutV1AdminLucro200RewardsItemMessages;
  id: string;
};

export type PutV1AdminLucro200Embed = {
  title: string;
  description: string;
  color: string;
  footer: string;
};

export type PutV1AdminLucro200 = {
  cooldownSeconds: number;
  rewards: PutV1AdminLucro200RewardsItem[];
  embed: PutV1AdminLucro200Embed;
};

export type GetV1AdminLucroSchema200VariablesItem = {
  token: string;
  description: string;
  example: string;
};

export type GetV1AdminLucroSchema200PropertiesTitle = {
  maxLength: number;
  examples: string[];
};

export type GetV1AdminLucroSchema200PropertiesDescription = {
  maxLength: number;
  examples: string[];
};

export type GetV1AdminLucroSchema200PropertiesColor = {
  maxLength: number;
  examples: string[];
};

export type GetV1AdminLucroSchema200PropertiesFooter = {
  maxLength: number;
  examples: string[];
};

export type GetV1AdminLucroSchema200Properties = {
  title: GetV1AdminLucroSchema200PropertiesTitle;
  description: GetV1AdminLucroSchema200PropertiesDescription;
  color: GetV1AdminLucroSchema200PropertiesColor;
  footer: GetV1AdminLucroSchema200PropertiesFooter;
};

export type GetV1AdminLucroSchema200 = {
  description: string;
  variables: GetV1AdminLucroSchema200VariablesItem[];
  properties: GetV1AdminLucroSchema200Properties;
};

export type JoinRankedQueueBody = {
  id: string;
  name: string;
  /** @nullable */
  avatarUrl: string | null;
};

export type JoinRankedQueue200 =
  | {
      kind: "waiting";
      division: {
        id: string;
        name: string;
        minimumPoints: number;
        emoji: string;
        /** @nullable */
        color: string | null;
        /** @nullable */
        imageUrl: string | null;
      };
    }
  | {
      kind: "matched";
      matchId: string;
    };

export type GetV1RankedStatusDiscordUserId200 =
  | {
      kind: "waiting";
      division: {
        id: string;
        name: string;
        minimumPoints: number;
        emoji: string;
        /** @nullable */
        color: string | null;
        /** @nullable */
        imageUrl: string | null;
      };
    }
  | null
  | {
      kind: "matched";
      matchId: string;
    };

export type GetV1LeagueDiscordUserId200Division = {
  id: string;
  name: string;
  minimumPoints: number;
  emoji: string;
  /** @nullable */
  color: string | null;
  /** @nullable */
  imageUrl: string | null;
};

export type GetV1LeagueDiscordUserId200Queue =
  | {
      kind: "waiting";
      division: {
        id: string;
        name: string;
        minimumPoints: number;
        emoji: string;
        /** @nullable */
        color: string | null;
        /** @nullable */
        imageUrl: string | null;
      };
    }
  | null
  | {
      kind: "matched";
      matchId: string;
    };

export type GetV1LeagueDiscordUserId200 = {
  points: number;
  wins: number;
  draws: number;
  losses: number;
  division: GetV1LeagueDiscordUserId200Division;
  queue: GetV1LeagueDiscordUserId200Queue;
};

export type GetV1MatchesMatchId200EventsItemType =
  (typeof GetV1MatchesMatchId200EventsItemType)[keyof typeof GetV1MatchesMatchId200EventsItemType];

export const GetV1MatchesMatchId200EventsItemType = {
  fulltime: "fulltime",
  goal: "goal",
  kickoff: "kickoff",
  red_card: "red_card",
  yellow_card: "yellow_card",
} as const;

export type GetV1MatchesMatchId200EventsItem = {
  sequence: number;
  minute: number;
  type: GetV1MatchesMatchId200EventsItemType;
  /** @nullable */
  playerUserCardId: string | null;
  /** @nullable */
  assistUserCardId: string | null;
  description: string;
  homeGoals: number;
  awayGoals: number;
};

export type GetV1MatchesMatchId200 = {
  id: string;
  homeUserId: string;
  awayUserId: string;
  homeGoals: number;
  awayGoals: number;
  completedAt: string;
  events: GetV1MatchesMatchId200EventsItem[];
};

export type HealthControllerHealth200Status =
  (typeof HealthControllerHealth200Status)[keyof typeof HealthControllerHealth200Status];

export const HealthControllerHealth200Status = {
  ok: "ok",
} as const;

export type HealthControllerHealth200 = {
  status: HealthControllerHealth200Status;
};

export type PurchaseCardBodyIdentity = {
  id: string;
  name: string;
  /** @nullable */
  avatarUrl: string | null;
};

export type PurchaseCardBody = {
  identity: PurchaseCardBodyIdentity;
};

export type PurchaseCard200 = {
  userCardId: string;
  balance: number;
  price: number;
};

export type SellCardsBodyIdentity = {
  id: string;
  name: string;
  /** @nullable */
  avatarUrl: string | null;
};

export type SellCardsBody = {
  identity: SellCardsBodyIdentity;
  userCardIds: string[];
};

export type SellCards200 = {
  userCardIds: string[];
  balance: number;
  amount: number;
};

export type PostV1AdminSessionBody = {
  apiKey: string;
};

export type PostV1AdminSession201 = {
  ok: boolean;
};

export type GetV1AdminSession200 = {
  ok: boolean;
};

export type GetV1AdminPacks200ItemConfigOnlyPositionsItem =
  (typeof GetV1AdminPacks200ItemConfigOnlyPositionsItem)[keyof typeof GetV1AdminPacks200ItemConfigOnlyPositionsItem];

export const GetV1AdminPacks200ItemConfigOnlyPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type GetV1AdminPacks200ItemConfigExcludedPositionsItem =
  (typeof GetV1AdminPacks200ItemConfigExcludedPositionsItem)[keyof typeof GetV1AdminPacks200ItemConfigExcludedPositionsItem];

export const GetV1AdminPacks200ItemConfigExcludedPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type GetV1AdminPacks200ItemConfig = {
  /** @nullable */
  name: string | null;
  minOverall: number;
  maxOverall: number;
  onlyPositions: GetV1AdminPacks200ItemConfigOnlyPositionsItem[];
  excludedPositions: GetV1AdminPacks200ItemConfigExcludedPositionsItem[];
  onlyCollectionIds: string[];
  excludedCollectionIds: string[];
  onlyCardIds: string[];
  excludedCardIds: string[];
  onlyTeamIds: string[];
  excludedTeamIds: string[];
  id: string;
};

export type GetV1AdminPacks200Item = {
  name: string;
  /** @nullable */
  imageUrl: string | null;
  color: string;
  emoji: string;
  cardsAmount: number;
  price: number;
  canBuy: boolean;
  limitPerUser: number;
  id: string;
  config: GetV1AdminPacks200ItemConfig;
};

export type PostV1AdminPacksBodyConfigOnlyPositionsItem =
  (typeof PostV1AdminPacksBodyConfigOnlyPositionsItem)[keyof typeof PostV1AdminPacksBodyConfigOnlyPositionsItem];

export const PostV1AdminPacksBodyConfigOnlyPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PostV1AdminPacksBodyConfigExcludedPositionsItem =
  (typeof PostV1AdminPacksBodyConfigExcludedPositionsItem)[keyof typeof PostV1AdminPacksBodyConfigExcludedPositionsItem];

export const PostV1AdminPacksBodyConfigExcludedPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PostV1AdminPacksBodyConfig = {
  /** @nullable */
  name: string | null;
  minOverall: number;
  maxOverall: number;
  onlyPositions: PostV1AdminPacksBodyConfigOnlyPositionsItem[];
  excludedPositions: PostV1AdminPacksBodyConfigExcludedPositionsItem[];
  onlyCollectionIds: string[];
  excludedCollectionIds: string[];
  onlyCardIds: string[];
  excludedCardIds: string[];
  onlyTeamIds: string[];
  excludedTeamIds: string[];
};

export type PostV1AdminPacksBody = {
  name: string;
  /** @nullable */
  imageUrl: string | null;
  color: string;
  emoji: string;
  cardsAmount: number;
  price: number;
  canBuy: boolean;
  limitPerUser: number;
  config: PostV1AdminPacksBodyConfig;
};

export type PostV1AdminPacks201ConfigOnlyPositionsItem =
  (typeof PostV1AdminPacks201ConfigOnlyPositionsItem)[keyof typeof PostV1AdminPacks201ConfigOnlyPositionsItem];

export const PostV1AdminPacks201ConfigOnlyPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PostV1AdminPacks201ConfigExcludedPositionsItem =
  (typeof PostV1AdminPacks201ConfigExcludedPositionsItem)[keyof typeof PostV1AdminPacks201ConfigExcludedPositionsItem];

export const PostV1AdminPacks201ConfigExcludedPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PostV1AdminPacks201Config = {
  /** @nullable */
  name: string | null;
  minOverall: number;
  maxOverall: number;
  onlyPositions: PostV1AdminPacks201ConfigOnlyPositionsItem[];
  excludedPositions: PostV1AdminPacks201ConfigExcludedPositionsItem[];
  onlyCollectionIds: string[];
  excludedCollectionIds: string[];
  onlyCardIds: string[];
  excludedCardIds: string[];
  onlyTeamIds: string[];
  excludedTeamIds: string[];
  id: string;
};

export type PostV1AdminPacks201 = {
  name: string;
  /** @nullable */
  imageUrl: string | null;
  color: string;
  emoji: string;
  cardsAmount: number;
  price: number;
  canBuy: boolean;
  limitPerUser: number;
  id: string;
  config: PostV1AdminPacks201Config;
};

export type PutV1AdminPacksIdBodyConfigOnlyPositionsItem =
  (typeof PutV1AdminPacksIdBodyConfigOnlyPositionsItem)[keyof typeof PutV1AdminPacksIdBodyConfigOnlyPositionsItem];

export const PutV1AdminPacksIdBodyConfigOnlyPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminPacksIdBodyConfigExcludedPositionsItem =
  (typeof PutV1AdminPacksIdBodyConfigExcludedPositionsItem)[keyof typeof PutV1AdminPacksIdBodyConfigExcludedPositionsItem];

export const PutV1AdminPacksIdBodyConfigExcludedPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminPacksIdBodyConfig = {
  /** @nullable */
  name: string | null;
  minOverall: number;
  maxOverall: number;
  onlyPositions: PutV1AdminPacksIdBodyConfigOnlyPositionsItem[];
  excludedPositions: PutV1AdminPacksIdBodyConfigExcludedPositionsItem[];
  onlyCollectionIds: string[];
  excludedCollectionIds: string[];
  onlyCardIds: string[];
  excludedCardIds: string[];
  onlyTeamIds: string[];
  excludedTeamIds: string[];
};

export type PutV1AdminPacksIdBody = {
  name: string;
  /** @nullable */
  imageUrl: string | null;
  color: string;
  emoji: string;
  cardsAmount: number;
  price: number;
  canBuy: boolean;
  limitPerUser: number;
  config: PutV1AdminPacksIdBodyConfig;
};

export type PutV1AdminPacksId200ConfigOnlyPositionsItem =
  (typeof PutV1AdminPacksId200ConfigOnlyPositionsItem)[keyof typeof PutV1AdminPacksId200ConfigOnlyPositionsItem];

export const PutV1AdminPacksId200ConfigOnlyPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminPacksId200ConfigExcludedPositionsItem =
  (typeof PutV1AdminPacksId200ConfigExcludedPositionsItem)[keyof typeof PutV1AdminPacksId200ConfigExcludedPositionsItem];

export const PutV1AdminPacksId200ConfigExcludedPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminPacksId200Config = {
  /** @nullable */
  name: string | null;
  minOverall: number;
  maxOverall: number;
  onlyPositions: PutV1AdminPacksId200ConfigOnlyPositionsItem[];
  excludedPositions: PutV1AdminPacksId200ConfigExcludedPositionsItem[];
  onlyCollectionIds: string[];
  excludedCollectionIds: string[];
  onlyCardIds: string[];
  excludedCardIds: string[];
  onlyTeamIds: string[];
  excludedTeamIds: string[];
  id: string;
};

export type PutV1AdminPacksId200 = {
  name: string;
  /** @nullable */
  imageUrl: string | null;
  color: string;
  emoji: string;
  cardsAmount: number;
  price: number;
  canBuy: boolean;
  limitPerUser: number;
  id: string;
  config: PutV1AdminPacksId200Config;
};

export type DeleteV1AdminPacksId200ConfigOnlyPositionsItem =
  (typeof DeleteV1AdminPacksId200ConfigOnlyPositionsItem)[keyof typeof DeleteV1AdminPacksId200ConfigOnlyPositionsItem];

export const DeleteV1AdminPacksId200ConfigOnlyPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type DeleteV1AdminPacksId200ConfigExcludedPositionsItem =
  (typeof DeleteV1AdminPacksId200ConfigExcludedPositionsItem)[keyof typeof DeleteV1AdminPacksId200ConfigExcludedPositionsItem];

export const DeleteV1AdminPacksId200ConfigExcludedPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type DeleteV1AdminPacksId200Config = {
  /** @nullable */
  name: string | null;
  minOverall: number;
  maxOverall: number;
  onlyPositions: DeleteV1AdminPacksId200ConfigOnlyPositionsItem[];
  excludedPositions: DeleteV1AdminPacksId200ConfigExcludedPositionsItem[];
  onlyCollectionIds: string[];
  excludedCollectionIds: string[];
  onlyCardIds: string[];
  excludedCardIds: string[];
  onlyTeamIds: string[];
  excludedTeamIds: string[];
  id: string;
};

export type DeleteV1AdminPacksId200 = {
  name: string;
  /** @nullable */
  imageUrl: string | null;
  color: string;
  emoji: string;
  cardsAmount: number;
  price: number;
  canBuy: boolean;
  limitPerUser: number;
  id: string;
  config: DeleteV1AdminPacksId200Config;
};

export type PutV1AdminPacksIdImage200ConfigOnlyPositionsItem =
  (typeof PutV1AdminPacksIdImage200ConfigOnlyPositionsItem)[keyof typeof PutV1AdminPacksIdImage200ConfigOnlyPositionsItem];

export const PutV1AdminPacksIdImage200ConfigOnlyPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminPacksIdImage200ConfigExcludedPositionsItem =
  (typeof PutV1AdminPacksIdImage200ConfigExcludedPositionsItem)[keyof typeof PutV1AdminPacksIdImage200ConfigExcludedPositionsItem];

export const PutV1AdminPacksIdImage200ConfigExcludedPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminPacksIdImage200Config = {
  /** @nullable */
  name: string | null;
  minOverall: number;
  maxOverall: number;
  onlyPositions: PutV1AdminPacksIdImage200ConfigOnlyPositionsItem[];
  excludedPositions: PutV1AdminPacksIdImage200ConfigExcludedPositionsItem[];
  onlyCollectionIds: string[];
  excludedCollectionIds: string[];
  onlyCardIds: string[];
  excludedCardIds: string[];
  onlyTeamIds: string[];
  excludedTeamIds: string[];
  id: string;
};

export type PutV1AdminPacksIdImage200 = {
  name: string;
  /** @nullable */
  imageUrl: string | null;
  color: string;
  emoji: string;
  cardsAmount: number;
  price: number;
  canBuy: boolean;
  limitPerUser: number;
  id: string;
  config: PutV1AdminPacksIdImage200Config;
};

export type GetV1AdminCardsCatalog200CollectionsItem = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type GetV1AdminCardsCatalog200TeamsItem = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type GetV1AdminCardsCatalog200 = {
  collections: GetV1AdminCardsCatalog200CollectionsItem[];
  teams: GetV1AdminCardsCatalog200TeamsItem[];
};

export type GetV1AdminCardsTeamLogoSuggestionsParams = {
  q: string;
};

export type GetV1AdminCardsTeamLogoSuggestions200Item = {
  name: string;
  slug: string;
  description: string;
  imageUrl: string;
  sourceUrl: string;
};

export type GetV1AdminCardsTeamLogoDetailsParams = {
  slug: string;
};

export type GetV1AdminCardsTeamLogoDetails200 = {
  name: string;
  slug: string;
  symbol: string;
  colors: string[];
  imageUrl: string;
  sourceUrl: string;
};

export type GetV1AdminCardsCollectionArtworkSuggestionsParams = {
  q: string;
};

export type GetV1AdminCardsCollectionArtworkSuggestions200Item = {
  name: string;
  slug: string;
  symbol: string;
  primaryColor: string;
  secondaryColor: string;
  imageUrl: string;
  overlayUrl: string;
  bannerUrl: string;
  description: string;
  sourceUrl: string;
};

export type GetV1AdminCardsPlayerPhotoSuggestionsParams = {
  q: string;
};

export type GetV1AdminCardsPlayerPhotoSuggestions200Item = {
  id: string;
  name: string;
  team: string;
  position: string;
  imageUrl: string;
  sourceUrl: string;
  provider: string;
};

export type GetV1AdminCardsCollectionsParams = {
  query?: string;
  page: number;
  pageSize?: number;
  contractsBlocked?: boolean;
};

export type GetV1AdminCardsCollections200ItemsItem = {
  slug: string;
  name: string;
  emoji: string;
  primaryColor: string;
  secondaryColor: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  overlayUrl?: string | null;
  /** @nullable */
  bannerUrl?: string | null;
  contractsBlocked?: boolean;
  id: string;
};

export type GetV1AdminCardsCollections200 = {
  items: GetV1AdminCardsCollections200ItemsItem[];
  total: number;
  page: number;
  pageSize: number;
};

export type PostV1AdminCardsCollectionsBody = {
  slug: string;
  name: string;
  emoji: string;
  primaryColor: string;
  secondaryColor: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  overlayUrl?: string | null;
  /** @nullable */
  bannerUrl?: string | null;
  contractsBlocked?: boolean;
};

export type PostV1AdminCardsCollections201 = {
  slug: string;
  name: string;
  emoji: string;
  primaryColor: string;
  secondaryColor: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  overlayUrl?: string | null;
  /** @nullable */
  bannerUrl?: string | null;
  contractsBlocked?: boolean;
  id: string;
};

export type PutV1AdminCardsCollectionsCollectionIdBody = {
  slug: string;
  name: string;
  emoji: string;
  primaryColor: string;
  secondaryColor: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  overlayUrl?: string | null;
  /** @nullable */
  bannerUrl?: string | null;
  contractsBlocked?: boolean;
};

export type PutV1AdminCardsCollectionsCollectionId200 = {
  slug: string;
  name: string;
  emoji: string;
  primaryColor: string;
  secondaryColor: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  overlayUrl?: string | null;
  /** @nullable */
  bannerUrl?: string | null;
  contractsBlocked?: boolean;
  id: string;
};

export type GetV1AdminCardsTeamsParams = {
  query?: string;
  page: number;
  pageSize?: number;
  image?: GetV1AdminCardsTeamsImage;
};

export type GetV1AdminCardsTeamsImage =
  (typeof GetV1AdminCardsTeamsImage)[keyof typeof GetV1AdminCardsTeamsImage];

export const GetV1AdminCardsTeamsImage = {
  custom: "custom",
  default: "default",
} as const;

export type GetV1AdminCardsTeams200ItemsItem = {
  slug: string;
  name: string;
  emoji: string;
  color: string;
  colors?: string[];
  /** @nullable */
  imageUrl?: string | null;
  id: string;
};

export type GetV1AdminCardsTeams200 = {
  items: GetV1AdminCardsTeams200ItemsItem[];
  total: number;
  page: number;
  pageSize: number;
};

export type PostV1AdminCardsTeamsBody = {
  slug: string;
  name: string;
  emoji: string;
  color: string;
  colors?: string[];
  /** @nullable */
  imageUrl?: string | null;
};

export type PostV1AdminCardsTeams201 = {
  slug: string;
  name: string;
  emoji: string;
  color: string;
  colors?: string[];
  /** @nullable */
  imageUrl?: string | null;
  id: string;
};

export type PutV1AdminCardsTeamsTeamIdBody = {
  slug: string;
  name: string;
  emoji: string;
  color: string;
  colors?: string[];
  /** @nullable */
  imageUrl?: string | null;
};

export type PutV1AdminCardsTeamsTeamId200 = {
  slug: string;
  name: string;
  emoji: string;
  color: string;
  colors?: string[];
  /** @nullable */
  imageUrl?: string | null;
  id: string;
};

export type GetV1AdminCardsTemplate200 = {
  filename: string;
  content: string;
};

export type PostV1AdminCardsPreview200ErrorsItem = {
  row: number;
  field: string;
  message: string;
};

export type PostV1AdminCardsPreview200 = {
  valid: boolean;
  createCount: number;
  updateCount: number;
  errors: PostV1AdminCardsPreview200ErrorsItem[];
};

export type PostV1AdminCardsImport200ErrorsItem = {
  row: number;
  field: string;
  message: string;
};

export type PostV1AdminCardsImport200 = {
  valid: boolean;
  createCount: number;
  updateCount: number;
  errors: PostV1AdminCardsImport200ErrorsItem[];
};

export type GetV1AdminCardsParams = {
  query?: string;
  collectionId?: string;
  teamId?: string;
  position?: GetV1AdminCardsPosition;
  image?: GetV1AdminCardsImage;
  contractsBlocked?: boolean;
  sort?: GetV1AdminCardsSort;
  page: number;
  pageSize?: number;
};

export type GetV1AdminCardsPosition =
  (typeof GetV1AdminCardsPosition)[keyof typeof GetV1AdminCardsPosition];

export const GetV1AdminCardsPosition = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type GetV1AdminCardsImage =
  (typeof GetV1AdminCardsImage)[keyof typeof GetV1AdminCardsImage];

export const GetV1AdminCardsImage = {
  custom: "custom",
  default: "default",
} as const;

export type GetV1AdminCardsSort =
  (typeof GetV1AdminCardsSort)[keyof typeof GetV1AdminCardsSort];

export const GetV1AdminCardsSort = {
  name: "name",
  overall: "overall",
  recent: "recent",
} as const;

export type GetV1AdminCards200ItemsItemCollection = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type GetV1AdminCards200ItemsItemTeam = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type GetV1AdminCards200ItemsItemPosition =
  (typeof GetV1AdminCards200ItemsItemPosition)[keyof typeof GetV1AdminCards200ItemsItemPosition];

export const GetV1AdminCards200ItemsItemPosition = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type GetV1AdminCards200ItemsItemSecondaryPositionsItem =
  (typeof GetV1AdminCards200ItemsItemSecondaryPositionsItem)[keyof typeof GetV1AdminCards200ItemsItemSecondaryPositionsItem];

export const GetV1AdminCards200ItemsItemSecondaryPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type GetV1AdminCards200ItemsItem = {
  id: string;
  slug: string;
  name: string;
  collection: GetV1AdminCards200ItemsItemCollection;
  team: GetV1AdminCards200ItemsItemTeam;
  position: GetV1AdminCards200ItemsItemPosition;
  secondaryPositions: GetV1AdminCards200ItemsItemSecondaryPositionsItem[];
  contractsBlocked: boolean;
  defense: number;
  attack: number;
  creation: number;
  overall: number;
  passing: number;
  control: number;
  marking: number;
  pace: number;
  dribbling: number;
  finishing: number;
  imageUrl: string;
};

export type GetV1AdminCards200 = {
  items: GetV1AdminCards200ItemsItem[];
  total: number;
  page: number;
  pageSize: number;
};

export type PostV1AdminCardsBodyPosition =
  (typeof PostV1AdminCardsBodyPosition)[keyof typeof PostV1AdminCardsBodyPosition];

export const PostV1AdminCardsBodyPosition = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PostV1AdminCardsBodySecondaryPositionsItem =
  (typeof PostV1AdminCardsBodySecondaryPositionsItem)[keyof typeof PostV1AdminCardsBodySecondaryPositionsItem];

export const PostV1AdminCardsBodySecondaryPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PostV1AdminCardsBody = {
  slug: string;
  name: string;
  collectionId: string;
  teamId: string;
  position: PostV1AdminCardsBodyPosition;
  secondaryPositions?: PostV1AdminCardsBodySecondaryPositionsItem[];
  contractsBlocked?: boolean;
  defense: number;
  attack: number;
  creation: number;
  overall: number;
  passing: number;
  control: number;
  marking: number;
  pace: number;
  dribbling: number;
  finishing: number;
};

export type PostV1AdminCards201Collection = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type PostV1AdminCards201Team = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type PostV1AdminCards201Position =
  (typeof PostV1AdminCards201Position)[keyof typeof PostV1AdminCards201Position];

export const PostV1AdminCards201Position = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PostV1AdminCards201SecondaryPositionsItem =
  (typeof PostV1AdminCards201SecondaryPositionsItem)[keyof typeof PostV1AdminCards201SecondaryPositionsItem];

export const PostV1AdminCards201SecondaryPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PostV1AdminCards201 = {
  id: string;
  slug: string;
  name: string;
  collection: PostV1AdminCards201Collection;
  team: PostV1AdminCards201Team;
  position: PostV1AdminCards201Position;
  secondaryPositions: PostV1AdminCards201SecondaryPositionsItem[];
  contractsBlocked: boolean;
  defense: number;
  attack: number;
  creation: number;
  overall: number;
  passing: number;
  control: number;
  marking: number;
  pace: number;
  dribbling: number;
  finishing: number;
  imageUrl: string;
};

export type GetV1AdminCardsCardId200Collection = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type GetV1AdminCardsCardId200Team = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type GetV1AdminCardsCardId200Position =
  (typeof GetV1AdminCardsCardId200Position)[keyof typeof GetV1AdminCardsCardId200Position];

export const GetV1AdminCardsCardId200Position = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type GetV1AdminCardsCardId200SecondaryPositionsItem =
  (typeof GetV1AdminCardsCardId200SecondaryPositionsItem)[keyof typeof GetV1AdminCardsCardId200SecondaryPositionsItem];

export const GetV1AdminCardsCardId200SecondaryPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type GetV1AdminCardsCardId200 = {
  id: string;
  slug: string;
  name: string;
  collection: GetV1AdminCardsCardId200Collection;
  team: GetV1AdminCardsCardId200Team;
  position: GetV1AdminCardsCardId200Position;
  secondaryPositions: GetV1AdminCardsCardId200SecondaryPositionsItem[];
  contractsBlocked: boolean;
  defense: number;
  attack: number;
  creation: number;
  overall: number;
  passing: number;
  control: number;
  marking: number;
  pace: number;
  dribbling: number;
  finishing: number;
  imageUrl: string;
};

export type PutV1AdminCardsCardIdBodyPosition =
  (typeof PutV1AdminCardsCardIdBodyPosition)[keyof typeof PutV1AdminCardsCardIdBodyPosition];

export const PutV1AdminCardsCardIdBodyPosition = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminCardsCardIdBodySecondaryPositionsItem =
  (typeof PutV1AdminCardsCardIdBodySecondaryPositionsItem)[keyof typeof PutV1AdminCardsCardIdBodySecondaryPositionsItem];

export const PutV1AdminCardsCardIdBodySecondaryPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminCardsCardIdBody = {
  name: string;
  collectionId: string;
  teamId: string;
  position: PutV1AdminCardsCardIdBodyPosition;
  secondaryPositions?: PutV1AdminCardsCardIdBodySecondaryPositionsItem[];
  contractsBlocked?: boolean;
  defense: number;
  attack: number;
  creation: number;
  overall: number;
  passing: number;
  control: number;
  marking: number;
  pace: number;
  dribbling: number;
  finishing: number;
};

export type PutV1AdminCardsCardId200Collection = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type PutV1AdminCardsCardId200Team = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type PutV1AdminCardsCardId200Position =
  (typeof PutV1AdminCardsCardId200Position)[keyof typeof PutV1AdminCardsCardId200Position];

export const PutV1AdminCardsCardId200Position = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminCardsCardId200SecondaryPositionsItem =
  (typeof PutV1AdminCardsCardId200SecondaryPositionsItem)[keyof typeof PutV1AdminCardsCardId200SecondaryPositionsItem];

export const PutV1AdminCardsCardId200SecondaryPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminCardsCardId200 = {
  id: string;
  slug: string;
  name: string;
  collection: PutV1AdminCardsCardId200Collection;
  team: PutV1AdminCardsCardId200Team;
  position: PutV1AdminCardsCardId200Position;
  secondaryPositions: PutV1AdminCardsCardId200SecondaryPositionsItem[];
  contractsBlocked: boolean;
  defense: number;
  attack: number;
  creation: number;
  overall: number;
  passing: number;
  control: number;
  marking: number;
  pace: number;
  dribbling: number;
  finishing: number;
  imageUrl: string;
};

export type PutV1AdminCardsCardIdImage200Collection = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type PutV1AdminCardsCardIdImage200Team = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type PutV1AdminCardsCardIdImage200Position =
  (typeof PutV1AdminCardsCardIdImage200Position)[keyof typeof PutV1AdminCardsCardIdImage200Position];

export const PutV1AdminCardsCardIdImage200Position = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminCardsCardIdImage200SecondaryPositionsItem =
  (typeof PutV1AdminCardsCardIdImage200SecondaryPositionsItem)[keyof typeof PutV1AdminCardsCardIdImage200SecondaryPositionsItem];

export const PutV1AdminCardsCardIdImage200SecondaryPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type PutV1AdminCardsCardIdImage200 = {
  id: string;
  slug: string;
  name: string;
  collection: PutV1AdminCardsCardIdImage200Collection;
  team: PutV1AdminCardsCardIdImage200Team;
  position: PutV1AdminCardsCardIdImage200Position;
  secondaryPositions: PutV1AdminCardsCardIdImage200SecondaryPositionsItem[];
  contractsBlocked: boolean;
  defense: number;
  attack: number;
  creation: number;
  overall: number;
  passing: number;
  control: number;
  marking: number;
  pace: number;
  dribbling: number;
  finishing: number;
  imageUrl: string;
};

export type DeleteV1AdminCardsCardIdImage200Collection = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type DeleteV1AdminCardsCardIdImage200Team = {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  /** @nullable */
  imageUrl: string | null;
};

export type DeleteV1AdminCardsCardIdImage200Position =
  (typeof DeleteV1AdminCardsCardIdImage200Position)[keyof typeof DeleteV1AdminCardsCardIdImage200Position];

export const DeleteV1AdminCardsCardIdImage200Position = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type DeleteV1AdminCardsCardIdImage200SecondaryPositionsItem =
  (typeof DeleteV1AdminCardsCardIdImage200SecondaryPositionsItem)[keyof typeof DeleteV1AdminCardsCardIdImage200SecondaryPositionsItem];

export const DeleteV1AdminCardsCardIdImage200SecondaryPositionsItem = {
  CA: "CA",
  GOL: "GOL",
  LD: "LD",
  LE: "LE",
  MA: "MA",
  MC: "MC",
  PD: "PD",
  PE: "PE",
  VOL: "VOL",
  ZAG: "ZAG",
} as const;

export type DeleteV1AdminCardsCardIdImage200 = {
  id: string;
  slug: string;
  name: string;
  collection: DeleteV1AdminCardsCardIdImage200Collection;
  team: DeleteV1AdminCardsCardIdImage200Team;
  position: DeleteV1AdminCardsCardIdImage200Position;
  secondaryPositions: DeleteV1AdminCardsCardIdImage200SecondaryPositionsItem[];
  contractsBlocked: boolean;
  defense: number;
  attack: number;
  creation: number;
  overall: number;
  passing: number;
  control: number;
  marking: number;
  pace: number;
  dribbling: number;
  finishing: number;
  imageUrl: string;
};

export const getListPackCatalogUrl = () => {
  return `/v1/packs`;
};

export const listPackCatalog = async (
  options?: Parameters<typeof request>[1],
): Promise<ListPackCatalog200Item[]> => {
  return request<ListPackCatalog200Item[]>(getListPackCatalogUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPackShopUrl = (params?: GetPackShopParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/packs/shop?${stringifiedParams}`
    : `/v1/packs/shop`;
};

export const getPackShop = async (
  params?: GetPackShopParams,
  options?: Parameters<typeof request>[1],
): Promise<ReadonlypacksReadonlyidstringnamestringpricenumberimageUrlstringcardsPerPacknumberpagenumbertotalPagesnumber> => {
  return request<ReadonlypacksReadonlyidstringnamestringpricenumberimageUrlstringcardsPerPacknumberpagenumbertotalPagesnumber>(
    getGetPackShopUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getInspectPackUrl = (packId: string) => {
  return `/v1/packs/${packId}`;
};

export const inspectPack = async (
  packId: string,
  options?: Parameters<typeof request>[1],
): Promise<ReadonlyidstringnamestringpricenumberimageUrlstringcardsPerPacknumber> => {
  return request<ReadonlyidstringnamestringpricenumberimageUrlstringcardsPerPacknumber>(
    getInspectPackUrl(packId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getPurchasePackUrl = (packId: string) => {
  return `/v1/packs/${packId}/purchase`;
};

export const purchasePack = async (
  packId: string,
  purchasePackBody: PurchasePackBody,
  options?: Parameters<typeof request>[1],
): Promise<PurchasePack200> => {
  return request<PurchasePack200>(getPurchasePackUrl(packId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(purchasePackBody),
  });
};

export const getOpenPackUrl = (packId: string) => {
  return `/v1/packs/${packId}/open`;
};

export const openPack = async (
  packId: string,
  openPackBody: OpenPackBody,
  options?: Parameters<typeof request>[1],
): Promise<OpenPack200> => {
  return request<OpenPack200>(getOpenPackUrl(packId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(openPackBody),
  });
};

export const getListMissionsUrl = () => {
  return `/v1/missions`;
};

export const listMissions = async (
  listMissionsBody: ListMissionsBody,
  options?: Parameters<typeof request>[1],
): Promise<ListMissions200> => {
  return request<ListMissions200>(getListMissionsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(listMissionsBody),
  });
};

export const getExecuteLucroUrl = () => {
  return `/v1/commands/lucro`;
};

/**
 * Executa o comando lucro.
 * @summary Executa o comando lucro
 */
export const executeLucro = async (
  executeLucroBody: ExecuteLucroBody,
  options?: Parameters<typeof request>[1],
): Promise<ExecuteLucro200> => {
  return request<ExecuteLucro200>(getExecuteLucroUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(executeLucroBody),
  });
};

export const getGetV1AdminLucroUrl = () => {
  return `/v1/admin/lucro`;
};

export const getV1AdminLucro = async (
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminLucro200> => {
  return request<GetV1AdminLucro200>(getGetV1AdminLucroUrl(), {
    ...options,
    method: "GET",
  });
};

export const getPutV1AdminLucroUrl = () => {
  return `/v1/admin/lucro`;
};

export const putV1AdminLucro = async (
  putV1AdminLucroBody: PutV1AdminLucroBody,
  options?: Parameters<typeof request>[1],
): Promise<PutV1AdminLucro200> => {
  return request<PutV1AdminLucro200>(getPutV1AdminLucroUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(putV1AdminLucroBody),
  });
};

export const getGetV1AdminLucroSchemaUrl = () => {
  return `/v1/admin/lucro/schema`;
};

export const getV1AdminLucroSchema = async (
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminLucroSchema200> => {
  return request<GetV1AdminLucroSchema200>(getGetV1AdminLucroSchemaUrl(), {
    ...options,
    method: "GET",
  });
};

export const getJoinRankedQueueUrl = () => {
  return `/v1/ranked/queue`;
};

export const joinRankedQueue = async (
  joinRankedQueueBody: JoinRankedQueueBody,
  options?: Parameters<typeof request>[1],
): Promise<JoinRankedQueue200> => {
  return request<JoinRankedQueue200>(getJoinRankedQueueUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(joinRankedQueueBody),
  });
};

export const getGetV1RankedStatusDiscordUserIdUrl = (discordUserId: string) => {
  return `/v1/ranked/status/${discordUserId}`;
};

export const getV1RankedStatusDiscordUserId = async (
  discordUserId: string,
  options?: Parameters<typeof request>[1],
): Promise<GetV1RankedStatusDiscordUserId200> => {
  return request<GetV1RankedStatusDiscordUserId200>(
    getGetV1RankedStatusDiscordUserIdUrl(discordUserId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetV1LeagueDiscordUserIdUrl = (discordUserId: string) => {
  return `/v1/league/${discordUserId}`;
};

export const getV1LeagueDiscordUserId = async (
  discordUserId: string,
  options?: Parameters<typeof request>[1],
): Promise<GetV1LeagueDiscordUserId200> => {
  return request<GetV1LeagueDiscordUserId200>(
    getGetV1LeagueDiscordUserIdUrl(discordUserId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetV1MatchesMatchIdUrl = (matchId: string) => {
  return `/v1/matches/${matchId}`;
};

export const getV1MatchesMatchId = async (
  matchId: string,
  options?: Parameters<typeof request>[1],
): Promise<GetV1MatchesMatchId200> => {
  return request<GetV1MatchesMatchId200>(getGetV1MatchesMatchIdUrl(matchId), {
    ...options,
    method: "GET",
  });
};

export const getHealthControllerHealthUrl = () => {
  return `/health`;
};

export const healthControllerHealth = async (
  options?: Parameters<typeof request>[1],
): Promise<HealthControllerHealth200> => {
  return request<HealthControllerHealth200>(getHealthControllerHealthUrl(), {
    ...options,
    method: "GET",
  });
};

export const getPurchaseCardUrl = (cardId: string) => {
  return `/v1/cards/${cardId}/purchase`;
};

export const purchaseCard = async (
  cardId: string,
  purchaseCardBody: PurchaseCardBody,
  options?: Parameters<typeof request>[1],
): Promise<PurchaseCard200> => {
  return request<PurchaseCard200>(getPurchaseCardUrl(cardId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(purchaseCardBody),
  });
};

export const getSellCardsUrl = () => {
  return `/v1/cards/sell`;
};

export const sellCards = async (
  sellCardsBody: SellCardsBody,
  options?: Parameters<typeof request>[1],
): Promise<SellCards200> => {
  return request<SellCards200>(getSellCardsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(sellCardsBody),
  });
};

export const getPostV1AdminSessionUrl = () => {
  return `/v1/admin/session`;
};

export const postV1AdminSession = async (
  postV1AdminSessionBody: PostV1AdminSessionBody,
  options?: Parameters<typeof request>[1],
): Promise<PostV1AdminSession201> => {
  return request<PostV1AdminSession201>(getPostV1AdminSessionUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postV1AdminSessionBody),
  });
};

export const getGetV1AdminSessionUrl = () => {
  return `/v1/admin/session`;
};

export const getV1AdminSession = async (
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminSession200> => {
  return request<GetV1AdminSession200>(getGetV1AdminSessionUrl(), {
    ...options,
    method: "GET",
  });
};

export const getDeleteV1AdminSessionUrl = () => {
  return `/v1/admin/session`;
};

export const deleteV1AdminSession = async (
  options?: Parameters<typeof request>[1],
): Promise<void> => {
  return request<void>(getDeleteV1AdminSessionUrl(), {
    ...options,
    method: "DELETE",
  });
};

export const getGetBotResponseSchemaUrl = () => {
  return `/v1/admin/bot-responses/schema`;
};

export const getBotResponseSchema = async (
  options?: Parameters<typeof request>[1],
): Promise<BotResponseDefinitionDto[]> => {
  return request<BotResponseDefinitionDto[]>(getGetBotResponseSchemaUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAdminBotResponseUrl = (key: string) => {
  return `/v1/admin/bot-responses/${key}`;
};

export const getAdminBotResponse = async (
  key: string,
  options?: Parameters<typeof request>[1],
): Promise<BotResponseTemplateDto> => {
  return request<BotResponseTemplateDto>(getGetAdminBotResponseUrl(key), {
    ...options,
    method: "GET",
  });
};

export const getUpdateBotResponseUrl = (key: string) => {
  return `/v1/admin/bot-responses/${key}`;
};

export const updateBotResponse = async (
  key: string,
  botResponseTemplateDto: BotResponseTemplateDto,
  options?: Parameters<typeof request>[1],
): Promise<BotResponseTemplateDto> => {
  return request<BotResponseTemplateDto>(getUpdateBotResponseUrl(key), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(botResponseTemplateDto),
  });
};

export const getGetBotResponseUrl = (key: string) => {
  return `/v1/bot-responses/${key}`;
};

export const getBotResponse = async (
  key: string,
  options?: Parameters<typeof request>[1],
): Promise<BotResponseTemplateDto> => {
  return request<BotResponseTemplateDto>(getGetBotResponseUrl(key), {
    ...options,
    method: "GET",
  });
};

export const getGetV1AdminPacksUrl = () => {
  return `/v1/admin/packs`;
};

export const getV1AdminPacks = async (
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminPacks200Item[]> => {
  return request<GetV1AdminPacks200Item[]>(getGetV1AdminPacksUrl(), {
    ...options,
    method: "GET",
  });
};

export const getPostV1AdminPacksUrl = () => {
  return `/v1/admin/packs`;
};

export const postV1AdminPacks = async (
  postV1AdminPacksBody: PostV1AdminPacksBody,
  options?: Parameters<typeof request>[1],
): Promise<PostV1AdminPacks201> => {
  return request<PostV1AdminPacks201>(getPostV1AdminPacksUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postV1AdminPacksBody),
  });
};

export const getPutV1AdminPacksIdUrl = (id: string) => {
  return `/v1/admin/packs/${id}`;
};

export const putV1AdminPacksId = async (
  id: string,
  putV1AdminPacksIdBody: PutV1AdminPacksIdBody,
  options?: Parameters<typeof request>[1],
): Promise<PutV1AdminPacksId200> => {
  return request<PutV1AdminPacksId200>(getPutV1AdminPacksIdUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(putV1AdminPacksIdBody),
  });
};

export const getDeleteV1AdminPacksIdUrl = (id: string) => {
  return `/v1/admin/packs/${id}`;
};

export const deleteV1AdminPacksId = async (
  id: string,
  options?: Parameters<typeof request>[1],
): Promise<DeleteV1AdminPacksId200> => {
  return request<DeleteV1AdminPacksId200>(getDeleteV1AdminPacksIdUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getPutV1AdminPacksIdImageUrl = (id: string) => {
  return `/v1/admin/packs/${id}/image`;
};

export const putV1AdminPacksIdImage = async (
  id: string,
  options?: Parameters<typeof request>[1],
): Promise<PutV1AdminPacksIdImage200> => {
  return request<PutV1AdminPacksIdImage200>(getPutV1AdminPacksIdImageUrl(id), {
    ...options,
    method: "PUT",
  });
};

export const getGetV1AdminCardsCatalogUrl = () => {
  return `/v1/admin/cards/catalog`;
};

export const getV1AdminCardsCatalog = async (
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminCardsCatalog200> => {
  return request<GetV1AdminCardsCatalog200>(getGetV1AdminCardsCatalogUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetV1AdminCardsTeamLogoSuggestionsUrl = (
  params: GetV1AdminCardsTeamLogoSuggestionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/admin/cards/team-logo-suggestions?${stringifiedParams}`
    : `/v1/admin/cards/team-logo-suggestions`;
};

export const getV1AdminCardsTeamLogoSuggestions = async (
  params: GetV1AdminCardsTeamLogoSuggestionsParams,
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminCardsTeamLogoSuggestions200Item[]> => {
  return request<GetV1AdminCardsTeamLogoSuggestions200Item[]>(
    getGetV1AdminCardsTeamLogoSuggestionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetV1AdminCardsTeamLogoDetailsUrl = (
  params: GetV1AdminCardsTeamLogoDetailsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/admin/cards/team-logo-details?${stringifiedParams}`
    : `/v1/admin/cards/team-logo-details`;
};

export const getV1AdminCardsTeamLogoDetails = async (
  params: GetV1AdminCardsTeamLogoDetailsParams,
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminCardsTeamLogoDetails200> => {
  return request<GetV1AdminCardsTeamLogoDetails200>(
    getGetV1AdminCardsTeamLogoDetailsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetV1AdminCardsTeamLogosFilenameUrl = (filename: string) => {
  return `/v1/admin/cards/team-logos/${filename}`;
};

export const getV1AdminCardsTeamLogosFilename = async (
  filename: string,
  options?: Parameters<typeof request>[1],
): Promise<void> => {
  return request<void>(getGetV1AdminCardsTeamLogosFilenameUrl(filename), {
    ...options,
    method: "GET",
  });
};

export const getGetV1AdminCardsCollectionArtworkSuggestionsUrl = (
  params: GetV1AdminCardsCollectionArtworkSuggestionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/admin/cards/collection-artwork-suggestions?${stringifiedParams}`
    : `/v1/admin/cards/collection-artwork-suggestions`;
};

export const getV1AdminCardsCollectionArtworkSuggestions = async (
  params: GetV1AdminCardsCollectionArtworkSuggestionsParams,
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminCardsCollectionArtworkSuggestions200Item[]> => {
  return request<GetV1AdminCardsCollectionArtworkSuggestions200Item[]>(
    getGetV1AdminCardsCollectionArtworkSuggestionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetV1AdminCardsPlayerPhotoSuggestionsUrl = (
  params: GetV1AdminCardsPlayerPhotoSuggestionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/admin/cards/player-photo-suggestions?${stringifiedParams}`
    : `/v1/admin/cards/player-photo-suggestions`;
};

export const getV1AdminCardsPlayerPhotoSuggestions = async (
  params: GetV1AdminCardsPlayerPhotoSuggestionsParams,
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminCardsPlayerPhotoSuggestions200Item[]> => {
  return request<GetV1AdminCardsPlayerPhotoSuggestions200Item[]>(
    getGetV1AdminCardsPlayerPhotoSuggestionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetV1AdminCardsPlayerPhotosFilenameUrl = (filename: string) => {
  return `/v1/admin/cards/player-photos/${filename}`;
};

export const getV1AdminCardsPlayerPhotosFilename = async (
  filename: string,
  options?: Parameters<typeof request>[1],
): Promise<void> => {
  return request<void>(getGetV1AdminCardsPlayerPhotosFilenameUrl(filename), {
    ...options,
    method: "GET",
  });
};

export const getGetV1AdminCardsPlayerPhotosKindFilenameUrl = (
  kind: string,
  filename: string,
) => {
  return `/v1/admin/cards/player-photos/${kind}/${filename}`;
};

export const getV1AdminCardsPlayerPhotosKindFilename = async (
  kind: string,
  filename: string,
  options?: Parameters<typeof request>[1],
): Promise<void> => {
  return request<void>(
    getGetV1AdminCardsPlayerPhotosKindFilenameUrl(kind, filename),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetV1AdminCardsCollectionsUrl = (
  params: GetV1AdminCardsCollectionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/admin/cards/collections?${stringifiedParams}`
    : `/v1/admin/cards/collections`;
};

export const getV1AdminCardsCollections = async (
  params: GetV1AdminCardsCollectionsParams,
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminCardsCollections200> => {
  return request<GetV1AdminCardsCollections200>(
    getGetV1AdminCardsCollectionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getPostV1AdminCardsCollectionsUrl = () => {
  return `/v1/admin/cards/collections`;
};

export const postV1AdminCardsCollections = async (
  postV1AdminCardsCollectionsBody: PostV1AdminCardsCollectionsBody,
  options?: Parameters<typeof request>[1],
): Promise<PostV1AdminCardsCollections201> => {
  return request<PostV1AdminCardsCollections201>(
    getPostV1AdminCardsCollectionsUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(postV1AdminCardsCollectionsBody),
    },
  );
};

export const getPutV1AdminCardsCollectionsCollectionIdUrl = (
  collectionId: string,
) => {
  return `/v1/admin/cards/collections/${collectionId}`;
};

export const putV1AdminCardsCollectionsCollectionId = async (
  collectionId: string,
  putV1AdminCardsCollectionsCollectionIdBody: PutV1AdminCardsCollectionsCollectionIdBody,
  options?: Parameters<typeof request>[1],
): Promise<PutV1AdminCardsCollectionsCollectionId200> => {
  return request<PutV1AdminCardsCollectionsCollectionId200>(
    getPutV1AdminCardsCollectionsCollectionIdUrl(collectionId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(putV1AdminCardsCollectionsCollectionIdBody),
    },
  );
};

export const getDeleteV1AdminCardsCollectionsCollectionIdUrl = (
  collectionId: string,
) => {
  return `/v1/admin/cards/collections/${collectionId}`;
};

export const deleteV1AdminCardsCollectionsCollectionId = async (
  collectionId: string,
  options?: Parameters<typeof request>[1],
): Promise<void> => {
  return request<void>(
    getDeleteV1AdminCardsCollectionsCollectionIdUrl(collectionId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getGetV1AdminCardsTeamsUrl = (
  params: GetV1AdminCardsTeamsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/admin/cards/teams?${stringifiedParams}`
    : `/v1/admin/cards/teams`;
};

export const getV1AdminCardsTeams = async (
  params: GetV1AdminCardsTeamsParams,
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminCardsTeams200> => {
  return request<GetV1AdminCardsTeams200>(getGetV1AdminCardsTeamsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getPostV1AdminCardsTeamsUrl = () => {
  return `/v1/admin/cards/teams`;
};

export const postV1AdminCardsTeams = async (
  postV1AdminCardsTeamsBody: PostV1AdminCardsTeamsBody,
  options?: Parameters<typeof request>[1],
): Promise<PostV1AdminCardsTeams201> => {
  return request<PostV1AdminCardsTeams201>(getPostV1AdminCardsTeamsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postV1AdminCardsTeamsBody),
  });
};

export const getPutV1AdminCardsTeamsTeamIdUrl = (teamId: string) => {
  return `/v1/admin/cards/teams/${teamId}`;
};

export const putV1AdminCardsTeamsTeamId = async (
  teamId: string,
  putV1AdminCardsTeamsTeamIdBody: PutV1AdminCardsTeamsTeamIdBody,
  options?: Parameters<typeof request>[1],
): Promise<PutV1AdminCardsTeamsTeamId200> => {
  return request<PutV1AdminCardsTeamsTeamId200>(
    getPutV1AdminCardsTeamsTeamIdUrl(teamId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(putV1AdminCardsTeamsTeamIdBody),
    },
  );
};

export const getDeleteV1AdminCardsTeamsTeamIdUrl = (teamId: string) => {
  return `/v1/admin/cards/teams/${teamId}`;
};

export const deleteV1AdminCardsTeamsTeamId = async (
  teamId: string,
  options?: Parameters<typeof request>[1],
): Promise<void> => {
  return request<void>(getDeleteV1AdminCardsTeamsTeamIdUrl(teamId), {
    ...options,
    method: "DELETE",
  });
};

export const getGetV1AdminCardsTemplateUrl = () => {
  return `/v1/admin/cards/template`;
};

export const getV1AdminCardsTemplate = async (
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminCardsTemplate200> => {
  return request<GetV1AdminCardsTemplate200>(getGetV1AdminCardsTemplateUrl(), {
    ...options,
    method: "GET",
  });
};

export const getPostV1AdminCardsPreviewUrl = () => {
  return `/v1/admin/cards/preview`;
};

export const postV1AdminCardsPreview = async (
  options?: Parameters<typeof request>[1],
): Promise<PostV1AdminCardsPreview200> => {
  return request<PostV1AdminCardsPreview200>(getPostV1AdminCardsPreviewUrl(), {
    ...options,
    method: "POST",
  });
};

export const getPostV1AdminCardsImportUrl = () => {
  return `/v1/admin/cards/import`;
};

export const postV1AdminCardsImport = async (
  options?: Parameters<typeof request>[1],
): Promise<PostV1AdminCardsImport200> => {
  return request<PostV1AdminCardsImport200>(getPostV1AdminCardsImportUrl(), {
    ...options,
    method: "POST",
  });
};

export const getGetV1AdminCardsUrl = (params: GetV1AdminCardsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/admin/cards?${stringifiedParams}`
    : `/v1/admin/cards`;
};

export const getV1AdminCards = async (
  params: GetV1AdminCardsParams,
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminCards200> => {
  return request<GetV1AdminCards200>(getGetV1AdminCardsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getPostV1AdminCardsUrl = () => {
  return `/v1/admin/cards`;
};

export const postV1AdminCards = async (
  postV1AdminCardsBody: PostV1AdminCardsBody,
  options?: Parameters<typeof request>[1],
): Promise<PostV1AdminCards201> => {
  return request<PostV1AdminCards201>(getPostV1AdminCardsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postV1AdminCardsBody),
  });
};

export const getGetV1AdminCardsCardIdUrl = (cardId: string) => {
  return `/v1/admin/cards/${cardId}`;
};

export const getV1AdminCardsCardId = async (
  cardId: string,
  options?: Parameters<typeof request>[1],
): Promise<GetV1AdminCardsCardId200> => {
  return request<GetV1AdminCardsCardId200>(
    getGetV1AdminCardsCardIdUrl(cardId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getPutV1AdminCardsCardIdUrl = (cardId: string) => {
  return `/v1/admin/cards/${cardId}`;
};

export const putV1AdminCardsCardId = async (
  cardId: string,
  putV1AdminCardsCardIdBody: PutV1AdminCardsCardIdBody,
  options?: Parameters<typeof request>[1],
): Promise<PutV1AdminCardsCardId200> => {
  return request<PutV1AdminCardsCardId200>(
    getPutV1AdminCardsCardIdUrl(cardId),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(putV1AdminCardsCardIdBody),
    },
  );
};

export const getDeleteV1AdminCardsCardIdUrl = (cardId: string) => {
  return `/v1/admin/cards/${cardId}`;
};

export const deleteV1AdminCardsCardId = async (
  cardId: string,
  options?: Parameters<typeof request>[1],
): Promise<void> => {
  return request<void>(getDeleteV1AdminCardsCardIdUrl(cardId), {
    ...options,
    method: "DELETE",
  });
};

export const getPutV1AdminCardsCardIdImageUrl = (cardId: string) => {
  return `/v1/admin/cards/${cardId}/image`;
};

export const putV1AdminCardsCardIdImage = async (
  cardId: string,
  options?: Parameters<typeof request>[1],
): Promise<PutV1AdminCardsCardIdImage200> => {
  return request<PutV1AdminCardsCardIdImage200>(
    getPutV1AdminCardsCardIdImageUrl(cardId),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getDeleteV1AdminCardsCardIdImageUrl = (cardId: string) => {
  return `/v1/admin/cards/${cardId}/image`;
};

export const deleteV1AdminCardsCardIdImage = async (
  cardId: string,
  options?: Parameters<typeof request>[1],
): Promise<DeleteV1AdminCardsCardIdImage200> => {
  return request<DeleteV1AdminCardsCardIdImage200>(
    getDeleteV1AdminCardsCardIdImageUrl(cardId),
    {
      ...options,
      method: "DELETE",
    },
  );
};
