/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Dreamfut API
 * Generated by nestia - https://github.com/samchon/nestia
 * OpenAPI spec version: 1.0
 */
import { request } from "./request.js";
/**
 * Estado atual do serviço.
 */
export type HealthResponseStatus =
  (typeof HealthResponseStatus)[keyof typeof HealthResponseStatus];

export const HealthResponseStatus = {
  ok: "ok",
} as const;

export interface HealthResponse {
  /** Estado atual do serviço. */
  status: HealthResponseStatus;
}

/**
 * Resultado com cooldown ainda ativo.
 */
export type LucroCooldownResponseKind =
  (typeof LucroCooldownResponseKind)[keyof typeof LucroCooldownResponseKind];

export const LucroCooldownResponseKind = {
  cooldown: "cooldown",
} as const;

export interface LucroCooldownResponse {
  /** Resultado com cooldown ainda ativo. */
  kind: LucroCooldownResponseKind;
  availableAt: string;
}

export interface LucroRewardDto {
  readonly value: number;
  readonly weight: number;
  readonly message: string;
}

/**
 * Resultado com recompensa concedida.
 */
export type LucroSuccessResponseKind =
  (typeof LucroSuccessResponseKind)[keyof typeof LucroSuccessResponseKind];

export const LucroSuccessResponseKind = {
  success: "success",
} as const;

export interface LucroSuccessResponse {
  /** Resultado com recompensa concedida. */
  kind: LucroSuccessResponseKind;
  reward: LucroRewardDto;
  balance: number;
  availableAt: string;
}

export interface DiscordIdentityDto {
  /**
   * @minLength 1
   * @maxLength 80
   */
  id: string;
  /**
   * @minLength 1
   * @maxLength 80
   */
  name: string;
  /**
   * @maxLength 2048
   * @nullable
   */
  avatarUrl: string | null;
}

export const getHealthControllerHealthUrl = () => {
  return `/health`;
};

export const healthControllerHealth = async (
  options?: Parameters<typeof request>[1],
): Promise<HealthResponse> => {
  return request<HealthResponse>(getHealthControllerHealthUrl(), {
    ...options,
    method: "GET",
  });
};

export const getExecuteLucroUrl = () => {
  return `/v1/commands/lucro`;
};

/**
 * Executa o comando lucro.
 * @summary Executa o comando lucro
 */
export const executeLucro = async (
  discordIdentityDto: DiscordIdentityDto,
  options?: Parameters<typeof request>[1],
): Promise<LucroCooldownResponse | LucroSuccessResponse> => {
  return request<LucroCooldownResponse | LucroSuccessResponse>(
    getExecuteLucroUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(discordIdentityDto),
    },
  );
};
