import type * as Generated from './generated.js';

export * from './generated.js';
export { ApiClientError, configureApiClient, request, type ApiClientOptions } from './request.js';
export type DiscordIdentityDto = Generated.ExecuteLucroBody;
export type BotResponseDefinitionDto = Generated.BotResponseDefinitionDto;
export type BotResponseTemplateDto = Generated.BotResponseTemplateDto;
export type LeagueStatusResponse = Generated.GetV1LeagueDiscordUserId200;
export type PackCatalogItem = Generated.ListPackCatalog200Item;
export type LucroConfigInputDto = Generated.PutV1AdminLucroBody;
export type MatchResponse = Generated.GetV1MatchesMatchId200;
export type MissionDtoCadence = Generated.ListMissions200MissionsItemCadence;
export type MissionsResponse = Generated.ListMissions200;
export type OpenPackResponse = Generated.OpenPack200;
export type PurchaseCardResponse = Generated.PurchaseCard200;
export type PurchasePackResponse = Generated.PurchasePack200;
export type PlayerPhotoSuggestion = Generated.GetV1AdminCardsPlayerPhotoSuggestions200Item;
export type QueueResponse = Generated.JoinRankedQueue200;
export type QueueMatchedResponse = Extract<QueueResponse, { kind: 'matched' }>;
export type QueueWaitingResponse = Extract<QueueResponse, { kind: 'waiting' }>;
export type QueueStatusResponse = Generated.GetV1RankedStatusDiscordUserId200;
export type QueueMatchedResponseNullable = Extract<QueueStatusResponse, { kind: 'matched' }> | null;
export type QueueWaitingResponseNullable = Extract<QueueStatusResponse, { kind: 'waiting' }> | null;
export type SellCardsResponse = Generated.SellCards200;
export type LucroResponse = Generated.ExecuteLucro200;
export type LucroCooldownResponse = Extract<LucroResponse, { kind: 'cooldown' }>;
export type LucroSuccessResponse = Extract<LucroResponse, { kind: 'success' }>;
